"""inicial

Revision ID: 0c771bc92658
Revises: 
Create Date: 2026-09-01 20:42:52.712168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c771bc92658'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_casos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_cliente', sa.String(length=255), nullable=False),
    sa.Column('identificacao_caso', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_canonicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_canonico', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_canonicos_categoria'), 'produtos_canonicos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_canonicos_nome_canonico'), 'produtos_canonicos', ['nome_canonico'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('achados_reconciliacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_canonico_id', sa.Integer(), nullable=False),
    sa.Column('cliente_caso_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VENDA_SEM_ESTOQUE', 'PRODUTO_SEM_ENTRADA', 'DIVERGENCIA_NOME', 'SALDO_NEGATIVO', 'OUTRO', name='tipoachado'), nullable=False),
    sa.Column('quantidade_entrada', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantidade_saida', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=True),
    sa.Column('periodo_fim', sa.DateTime(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_caso_id'], ['clientes_casos.id'], ),
    sa.ForeignKeyConstraint(['produto_canonico_id'], ['produtos_canonicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achados_reconciliacao_cliente_caso_id'), 'achados_reconciliacao', ['cliente_caso_id'], unique=False)
    op.create_index(op.f('ix_achados_reconciliacao_produto_canonico_id'), 'achados_reconciliacao', ['produto_canonico_id'], unique=False)
    op.create_index(op.f('ix_achados_reconciliacao_tipo'), 'achados_reconciliacao', ['tipo'], unique=False)
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=120), nullable=False),
    sa.Column('pergunta_usuario', sa.Text(), nullable=True),
    sa.Column('sql_gerado', sa.Text(), nullable=True),
    sa.Column('resultado_resumo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_criado_em'), 'logs_auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_usuario_id'), 'logs_auditoria', ['usuario_id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tiponota'), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('emitente_cnpj', sa.String(length=14), nullable=True),
    sa.Column('emitente_nome', sa.String(length=255), nullable=True),
    sa.Column('destinatario_cnpj', sa.String(length=14), nullable=True),
    sa.Column('destinatario_nome', sa.String(length=255), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cliente_caso_id', sa.Integer(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_caso_id'], ['clientes_casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_chave_acesso'), 'notas', ['chave_acesso'], unique=True)
    op.create_index(op.f('ix_notas_cliente_caso_id'), 'notas', ['cliente_caso_id'], unique=False)
    op.create_index(op.f('ix_notas_destinatario_cnpj'), 'notas', ['destinatario_cnpj'], unique=False)
    op.create_index(op.f('ix_notas_emitente_cnpj'), 'notas', ['emitente_cnpj'], unique=False)
    op.create_index(op.f('ix_notas_tipo'), 'notas', ['tipo'], unique=False)
    op.create_table('itens_nota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=True),
    sa.Column('codigo_produto', sa.String(length=60), nullable=True),
    sa.Column('descricao_original', sa.String(length=500), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('produto_canonico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.ForeignKeyConstraint(['produto_canonico_id'], ['produtos_canonicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_nota_cfop'), 'itens_nota', ['cfop'], unique=False)
    op.create_index(op.f('ix_itens_nota_ncm'), 'itens_nota', ['ncm'], unique=False)
    op.create_index(op.f('ix_itens_nota_nota_id'), 'itens_nota', ['nota_id'], unique=False)
    op.create_index(op.f('ix_itens_nota_produto_canonico_id'), 'itens_nota', ['produto_canonico_id'], unique=False)
    op.create_table('sugestoes_normalizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_nota_id', sa.Integer(), nullable=False),
    sa.Column('produto_canonico_sugerido_id', sa.Integer(), nullable=False),
    sa.Column('confianca', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'REJEITADO', name='statusrevisao'), nullable=True),
    sa.Column('revisado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('revisado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_nota_id'], ['itens_nota.id'], ),
    sa.ForeignKeyConstraint(['produto_canonico_sugerido_id'], ['produtos_canonicos.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sugestoes_normalizacao_item_nota_id'), 'sugestoes_normalizacao', ['item_nota_id'], unique=False)
    op.create_index(op.f('ix_sugestoes_normalizacao_status'), 'sugestoes_normalizacao', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sugestoes_normalizacao_status'), table_name='sugestoes_normalizacao')
    op.drop_index(op.f('ix_sugestoes_normalizacao_item_nota_id'), table_name='sugestoes_normalizacao')
    op.drop_table('sugestoes_normalizacao')
    op.drop_index(op.f('ix_itens_nota_produto_canonico_id'), table_name='itens_nota')
    op.drop_index(op.f('ix_itens_nota_nota_id'), table_name='itens_nota')
    op.drop_index(op.f('ix_itens_nota_ncm'), table_name='itens_nota')
    op.drop_index(op.f('ix_itens_nota_cfop'), table_name='itens_nota')
    op.drop_table('itens_nota')
    op.drop_index(op.f('ix_notas_tipo'), table_name='notas')
    op.drop_index(op.f('ix_notas_emitente_cnpj'), table_name='notas')
    op.drop_index(op.f('ix_notas_destinatario_cnpj'), table_name='notas')
    op.drop_index(op.f('ix_notas_cliente_caso_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_chave_acesso'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_logs_auditoria_usuario_id'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_criado_em'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_index(op.f('ix_achados_reconciliacao_tipo'), table_name='achados_reconciliacao')
    op.drop_index(op.f('ix_achados_reconciliacao_produto_canonico_id'), table_name='achados_reconciliacao')
    op.drop_index(op.f('ix_achados_reconciliacao_cliente_caso_id'), table_name='achados_reconciliacao')
    op.drop_table('achados_reconciliacao')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_canonicos_nome_canonico'), table_name='produtos_canonicos')
    op.drop_index(op.f('ix_produtos_canonicos_categoria'), table_name='produtos_canonicos')
    op.drop_table('produtos_canonicos')
    op.drop_table('clientes_casos')
    # ### end Alembic commands ###
