"""auth cadastro usuarios com aprovacao

Revision ID: baf1eebe0db2
Revises: 0c771bc92658
Create Date: 2026-09-01 20:44:01.484450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'baf1eebe0db2'
down_revision: Union[str, Sequence[str], None] = '0c771bc92658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.Enum('COMUM', 'ADMINISTRADOR', name='roleusuario'), nullable=False))
    op.add_column('usuarios', sa.Column('status_cadastro', sa.Enum('PENDENTE', 'APROVADO', 'REPROVADO', name='statuscadastro'), nullable=False))
    op.add_column('usuarios', sa.Column('aprovado_por_usuario_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('aprovado_em', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('usuarios', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.create_index(op.f('ix_usuarios_role'), 'usuarios', ['role'], unique=False)
    op.create_index(op.f('ix_usuarios_status_cadastro'), 'usuarios', ['status_cadastro'], unique=False)
    op.create_foreign_key(
        'fk_usuarios_aprovado_por_usuario_id_usuarios',
        'usuarios', 'usuarios', ['aprovado_por_usuario_id'], ['id'],
    )
    op.drop_column('usuarios', 'senha_hash')
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('senha_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint('fk_usuarios_aprovado_por_usuario_id_usuarios', 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_status_cadastro'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_role'), table_name='usuarios')
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=320),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('usuarios', 'is_verified')
    op.drop_column('usuarios', 'is_superuser')
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'hashed_password')
    op.drop_column('usuarios', 'aprovado_em')
    op.drop_column('usuarios', 'aprovado_por_usuario_id')
    op.drop_column('usuarios', 'status_cadastro')
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
